; Auto-generated. Do not edit!


(cl:in-package newmsg-msg)


;//! \htmlinclude pf.msg.html

(cl:defclass <pf> (roslisp-msg-protocol:ros-message)
  ((p_1
    :reader p_1
    :initarg :p_1
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (p_2
    :reader p_2
    :initarg :p_2
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (p_3
    :reader p_3
    :initarg :p_3
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (p_4
    :reader p_4
    :initarg :p_4
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (p_5
    :reader p_5
    :initarg :p_5
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass pf (<pf>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pf>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pf)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name newmsg-msg:<pf> is deprecated: use newmsg-msg:pf instead.")))

(cl:ensure-generic-function 'p_1-val :lambda-list '(m))
(cl:defmethod p_1-val ((m <pf>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader newmsg-msg:p_1-val is deprecated.  Use newmsg-msg:p_1 instead.")
  (p_1 m))

(cl:ensure-generic-function 'p_2-val :lambda-list '(m))
(cl:defmethod p_2-val ((m <pf>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader newmsg-msg:p_2-val is deprecated.  Use newmsg-msg:p_2 instead.")
  (p_2 m))

(cl:ensure-generic-function 'p_3-val :lambda-list '(m))
(cl:defmethod p_3-val ((m <pf>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader newmsg-msg:p_3-val is deprecated.  Use newmsg-msg:p_3 instead.")
  (p_3 m))

(cl:ensure-generic-function 'p_4-val :lambda-list '(m))
(cl:defmethod p_4-val ((m <pf>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader newmsg-msg:p_4-val is deprecated.  Use newmsg-msg:p_4 instead.")
  (p_4 m))

(cl:ensure-generic-function 'p_5-val :lambda-list '(m))
(cl:defmethod p_5-val ((m <pf>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader newmsg-msg:p_5-val is deprecated.  Use newmsg-msg:p_5 instead.")
  (p_5 m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pf>) ostream)
  "Serializes a message object of type '<pf>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'p_1))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'p_1))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'p_2))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'p_2))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'p_3))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'p_3))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'p_4))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'p_4))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'p_5))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'p_5))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pf>) istream)
  "Deserializes a message object of type '<pf>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'p_1) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'p_1)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'p_2) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'p_2)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'p_3) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'p_3)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'p_4) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'p_4)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'p_5) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'p_5)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pf>)))
  "Returns string type for a message object of type '<pf>"
  "newmsg/pf")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pf)))
  "Returns string type for a message object of type 'pf"
  "newmsg/pf")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pf>)))
  "Returns md5sum for a message object of type '<pf>"
  "d83cd7bb6bd06c328faaefd30fb67de3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pf)))
  "Returns md5sum for a message object of type 'pf"
  "d83cd7bb6bd06c328faaefd30fb67de3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pf>)))
  "Returns full string definition for message of type '<pf>"
  (cl:format cl:nil "float32[] p_1~%float32[] p_2~%float32[] p_3~%float32[] p_4~%float32[] p_5~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pf)))
  "Returns full string definition for message of type 'pf"
  (cl:format cl:nil "float32[] p_1~%float32[] p_2~%float32[] p_3~%float32[] p_4~%float32[] p_5~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pf>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'p_1) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'p_2) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'p_3) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'p_4) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'p_5) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pf>))
  "Converts a ROS message object to a list"
  (cl:list 'pf
    (cl:cons ':p_1 (p_1 msg))
    (cl:cons ':p_2 (p_2 msg))
    (cl:cons ':p_3 (p_3 msg))
    (cl:cons ':p_4 (p_4 msg))
    (cl:cons ':p_5 (p_5 msg))
))
